const 词典={industrial_policy:"产业政策",technology:"技术",investment:"投资",trade:"贸易",energy_resources:"能源与资源",supply_chain:"供应链",data_platform:"数据与平台",international_cooperation:"国际合作",infrastructure:"基础设施",finance:"金融",security:"安全",resilience:"韧性",competitiveness:"竞争力",human_rights:"人权",environment:"环境与气候",other:"其他",effective:"生效",terminated:"终止",amended:"修订",suspended:"暂停",proposed:"草案／提议",adopted:"已通过",promote:"促进",restrict:"限制",defend:"防御",retaliate:"反制",cooperate:"合作",capacity_building:"能力建设",export_control:"出口管制",entity_listing:"实体清单",industrial_strategy:"产业战略",subsidy:"补贴",tax_incentive:"税收激励",inward_investment_screening:"外资安全审查",outbound_investment_screening:"对外投资审查",critical_mineral_policy:"关键矿产政策",strategic_funding_platform:"战略融资平台",supply_chain_review:"供应链审查／战略",economic_security_partnership:"经济安全伙伴关系",tariff:"关税",trade_countermeasure:"贸易反制",import_restriction:"进口限制",financial_sanction:"金融制裁",procurement_preference:"政府采购偏好",supply_chain_agreement:"供应链协议",traceability_due_diligence:"追溯与尽职调查",foreign_subsidy_review:"外国补贴审查",digital_technology_control:"数字技术管制",cross_border_data_rule:"跨境数据规则",cross_border_data_restriction:"跨境数据限制",infrastructure_financing:"基础设施融资",production_mandate:"生产要求",resource_export_restriction:"资源出口限制"};
const 译=x=>词典[x]||String(x||"").replaceAll("_"," ");
const $=x=>document.querySelector(x);let 全部=[],视图="timeline";
const 统计=(a,k)=>Object.entries(a.reduce((o,p)=>{const v=p[k]||"未标明";o[v]=(o[v]||0)+1;return o},{})).sort((a,b)=>b[1]-a[1]);
fetch("./policies.json?v=12").then(r=>{if(!r.ok)throw Error(`数据读取失败：${r.status}`);return r.json()}).then(x=>{全部=x;total.textContent=x.length;totalEconomies.textContent=new Set(x.map(p=>p.economy)).size;初始化();呈现()}).catch(e=>canvas.innerHTML=`<p class="error">${e.message}，请刷新页面或检查数据文件。</p>`);
function 选项(id,items,翻译=true){$(id).innerHTML='<option value="全部">全部</option>'+items.map(([v,n])=>`<option value="${v}">${翻译?译(v):v}（${n}）</option>`).join("")}
function 初始化(){选项("#economy",统计(全部,"economy"),false);选项("#domain",统计(全部,"domain"));选项("#purpose",统计(全部,"rationale"));选项("#status",统计(全部,"status"));for(let y=2015;y<=2026;y++){from.add(new Option(y,y));to.add(new Option(y,y))}from.value=2015;to.value=2026;document.querySelectorAll("input,select").forEach(e=>e.oninput=呈现);reset.onclick=()=>{q.value="";economy.value=domain.value=purpose.value=status.value="全部";from.value=2015;to.value=2026;呈现()};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{视图=b.dataset.view;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));呈现()});close.onclick=()=>detail.close()}
function 筛选(){const s=q.value.trim().toLowerCase();return 全部.filter(p=>(economy.value==="全部"||p.economy===economy.value)&&(domain.value==="全部"||p.domain===domain.value)&&(purpose.value==="全部"||p.rationale===purpose.value)&&(status.value==="全部"||p.status===status.value)&&+p.announced.slice(0,4)>=+from.value&&+p.announced.slice(0,4)<=+to.value&&(!s||[p.name,p.originalName,p.authority,p.summary,p.instrument,p.targetIndustry].join(" ").toLowerCase().includes(s)))}
function 呈现(){const a=筛选();count.textContent=a.length;ecount.textContent=new Set(a.map(p=>p.economy)).size;active.textContent=a.filter(p=>p.status==="effective").length;verify.textContent=a.filter(p=>p.uncertain).length;({timeline:时间线,compare:比较,tools:工具,intensity:强度,table:明细}[视图])(a)}
function 图例(es){return `<div class="legend">${es.map(([e],i)=>`<span><i data-i="${i%4}"></i>${e}</span>`).join("")}</div>`}
function 时间线(a){const es=统计(a,"economy"),ys=[];for(let y=+from.value;y<=+to.value;y++)ys.push(y);const rows=ys.map(y=>({year:y,bars:es.map(([e],i)=>({e,i,n:a.filter(p=>p.economy===e&&p.announced.startsWith(String(y))).length})).filter(x=>x.n).sort((x,z)=>z.n-x.n||x.i-z.i)})),max=Math.max(1,...rows.map(r=>r.bars.reduce((s,x)=>s+x.n,0)));canvas.innerHTML=`<div class="timeline">${图例(es)}${rows.map(r=>`<div class="yearrow"><b>${r.year}</b><div>${r.bars.map(x=>`<button data-i="${x.i%4}" style="width:${x.n/max*100}%" title="${r.year}年 ${x.e}：${x.n}项">${x.e} ${x.n}</button>`).join("")}</div></div>`).join("")}</div>`}
const 色=["#0c7568","#c58a2b","#39738a","#a64d3f","#6f8f3d","#76518f","#2f8f9d","#9a6d35","#536f91","#8f5066"];
function 比较(a){const es=统计(a,"economy"),ds=统计(a,"domain"),m=Math.max(1,...es.map(x=>x[1]));canvas.innerHTML=`<div class="compare"><h2>经济体政策构成</h2><div class="legend policy-legend"><b>政策领域</b>${ds.map(([d],i)=>`<span><i style="background:${色[i%色.length]}"></i>${译(d)}</span>`).join("")}</div>${es.map(([e,n])=>`<div class="compareblock"><header style="width:${n/m*100}%"><b>${e}</b><span>${n}项</span></header><div class="stack" style="width:${n/m*100}%">${ds.map(([d],i)=>{const c=a.filter(p=>p.economy===e&&p.domain===d).length;return c?`<i title="${译(d)}：${c}项" style="width:${c/n*100}%;background:${色[i%色.length]}"></i>`:""}).join("")}</div></div>`).join("")}</div>`}
function 工具(a){const ds=统计(a,"domain"),ts=统计(a,"instrument").slice(0,12),max=Math.max(1,...ds.flatMap(([d])=>ts.map(([t])=>a.filter(p=>p.domain===d&&p.instrument===t).length)));canvas.innerHTML=`<div class="matrixwrap"><h2>领域 × 政策工具</h2><div class="matrix" style="grid-template-columns:150px repeat(${ts.length},minmax(110px,1fr))"><span></span>${ts.map(([t])=>`<b>${译(t)}</b>`).join("")}${ds.map(([d])=>`<strong>${译(d)}</strong>${ts.map(([t])=>{const n=a.filter(p=>p.domain===d&&p.instrument===t).length;return `<i style="opacity:${n?.18+.82*n/max:0}">${n||""}</i>`}).join("")}`).join("")}</div></div>`}
function 强度(a){const es=统计(a,"economy");canvas.innerHTML=`<div class="tablewrap"><h2>强度维度均值（预编码探索，不是综合排名）</h2><p>数值仅用于发现结构差异；“机器预编码”尚不能作为最终实证变量。</p><table><thead><tr><th>经济体</th><th>法律层级</th><th>覆盖范围</th><th>约束程度</th><th>实施范围</th><th>需第二编码</th></tr></thead><tbody>${es.map(([e])=>{const x=a.filter(p=>p.economy===e),avg=k=>(x.reduce((s,p)=>s+(+p[k]||0),0)/x.filter(p=>p[k]).length).toFixed(2);return `<tr><td><b>${e}</b></td><td>${avg("legalScore")}</td><td>${avg("coverageScore")}</td><td>${avg("coercivenessScore")}</td><td>${avg("scopeScore")}</td><td>${x.filter(p=>p.reviewStatus!=="dual_reviewed").length}</td></tr>`}).join("")}</tbody></table></div>`}
function 明细(a){canvas.innerHTML=`<div class="tablewrap"><table><thead><tr><th>日期</th><th>经济体</th><th>政策</th><th>领域／工具</th><th>目的</th><th>状态</th><th>关系</th><th>复核</th></tr></thead><tbody>${[...a].sort((x,y)=>y.announced.localeCompare(x.announced)).map(p=>`<tr data-id="${p.id}"><td>${p.announced}</td><td>${p.economy}</td><td><b>${p.name}</b><small>${p.authority}</small></td><td>${译(p.domain)}<small>${译(p.instrument)}</small></td><td>${译(p.rationale)}</td><td><span class="status-pill ${p.status}">${译(p.status)}</span></td><td>${p.relationCount||0}</td><td>${p.reviewStatus==="dual_reviewed"?"双人复核":"待第二编码"}</td></tr>`).join("")}</tbody></table></div>`;canvas.querySelectorAll("tr[data-id]").forEach(r=>r.onclick=()=>详情(全部.find(p=>p.id===r.dataset.id)))}
function 详情(p){detailbody.innerHTML=`<p>记录编号：${p.id}　经济体：${p.economy}</p><h2>${p.name}</h2><p><b>公布：</b>${p.announced}　<b>生效：</b>${p.effective||"未标明"}　<b>状态：</b>${译(p.status)}</p><h3>政策摘要</h3><p>${p.summary}</p><h3>政策分类</h3><p>${译(p.domain)} · ${译(p.instrument)} · ${译(p.direction)} · ${译(p.rationale)}</p><h3>强度分项</h3><p>法律层级 ${p.legalScore||"待编码"}；覆盖范围 ${p.coverageScore||"待编码"}；约束程度 ${p.coercivenessScore||"待编码"}；实施范围 ${p.scopeScore||"待编码"}。复核状态：${p.reviewStatus==="dual_reviewed"?"双人复核完成":"待第二编码"}。</p><h3>关系与证据</h3><p>已关联 ${p.relationCount||0} 项政策事件。</p><a href="${p.sourceUrl}" target="_blank" rel="noopener">查看官方原文 →</a><p>最后核验：${p.verified}</p>${p.notes?`<p>${p.notes}</p>`:""}`;detail.showModal()}
