const Z={industrial_policy:"产业政策",technology:"技术",investment:"投资",trade:"贸易",energy_resources:"能源与资源",supply_chain:"供应链",data_platform:"数据与平台",international_cooperation:"国际合作",infrastructure:"基础设施",finance:"金融",security:"安全与韧性",resilience:"供应链韧性",competitiveness:"竞争力",human_rights:"人权",environment:"环境与气候",other:"其他",effective:"生效",terminated:"终止",amended:"修订",suspended:"暂停",proposed:"提议",adopted:"已通过",promote:"促进",restrict:"限制",defend:"防御",retaliate:"反制",cooperate:"合作",capacity_building:"能力建设",binding:"约束性",non_binding:"非约束性",mixed:"混合",industrial_strategy:"产业战略",critical_mineral_policy:"关键矿产政策",export_control:"出口管制",inward_investment_screening:"外资安全审查",outbound_investment_screening:"对外投资审查",subsidy:"补贴",tariff:"关税",tax_incentive:"税收激励",supply_chain_review:"供应链审查",supply_chain_agreement:"供应链协议",trade_countermeasure:"贸易反制",import_restriction:"进口限制",strategic_funding_platform:"战略融资平台",global:"全球",countries_of_concern:"受关注国家",China:"中国",Russia:"俄罗斯"};
const L=x=>Z[x]||String(x||"").replaceAll("_"," ");let all=[],view="timeline";const $=x=>document.querySelector(x),counts=(a,k)=>Object.entries(a.reduce((o,p)=>(o[p[k]||"未标明"]=(o[p[k]||"未标明"]||0)+1,o),{})).sort((a,b)=>b[1]-a[1]);
fetch("policies.json").then(r=>r.json()).then(x=>{all=x;$("#total").textContent=x.length;setup();render()});
function options(id,items,label=true){$(id).innerHTML='<option value="全部">全部</option>'+items.map(([v,n])=>`<option value="${v}">${label?L(v):v}（${n}）</option>`).join("")}
function setup(){options("#economy",counts(all,"economy"),false);options("#domain",counts(all,"domain"));options("#purpose",counts(all,"rationale"));options("#status",counts(all,"status"));for(let y=2015;y<=2026;y++){from.add(new Option(y,y));to.add(new Option(y,y))}from.value=2015;to.value=2026;document.querySelectorAll("input,select").forEach(e=>e.oninput=render);reset.onclick=()=>{q.value="";economy.value=domain.value=purpose.value=status.value="全部";from.value=2015;to.value=2026;render()};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("on",x===b));render()});close.onclick=()=>detail.close()}
function filtered(){let s=q.value.trim().toLowerCase();return all.filter(p=>(economy.value==="全部"||p.economy===economy.value)&&(domain.value==="全部"||p.domain===domain.value)&&(purpose.value==="全部"||p.rationale===purpose.value)&&(status.value==="全部"||p.status===status.value)&&+p.announced.slice(0,4)>=+from.value&&+p.announced.slice(0,4)<=+to.value&&(!s||[p.name,p.originalName,p.authority,p.summary,p.instrument,p.targetIndustry].join(" ").toLowerCase().includes(s)))}
function render(){let a=filtered();count.textContent=a.length;ecount.textContent=new Set(a.map(p=>p.economy)).size;active.textContent=a.filter(p=>p.status==="effective").length;verify.textContent=a.filter(p=>p.uncertain).length;({timeline,compare,tools,table}[view])(a)}
function timeline(a){let es=counts(a,"economy"),ys=[];for(let y=+from.value;y<=+to.value;y++)ys.push(y);let max=Math.max(1,...ys.flatMap(y=>es.map(([e])=>a.filter(p=>p.economy===e&&p.announced.startsWith(y)).length)));canvas.innerHTML=ys.map(y=>`<div class="year"><b>${y}</b><div class="bars">${es.map(([e])=>{let n=a.filter(p=>p.economy===e&&p.announced.startsWith(y)).length;return n?`<button class="bar" style="width:${Math.max(5,n/max*100)}%">${e} ${n}</button>`:""}).join("")}</div></div>`).join("")}
function compare(a){let c=counts(a,"economy"),m=Math.max(1,...c.map(x=>x[1]));canvas.innerHTML='<h2>经济体政策构成</h2>'+c.map(([e,n])=>`<div class="compare-row"><header><b>${e}</b><span>${n}项</span></header><div class="track"><i style="width:${n/m*100}%"></i></div></div>`).join("")}
function tools(a){let ds=counts(a,"domain"),ts=counts(a,"instrument").slice(0,12);canvas.innerHTML=`<table class="matrix"><tr><th>领域 × 工具</th>${ts.map(([t])=>`<th>${L(t)}</th>`).join("")}</tr>${ds.map(([d])=>`<tr><th>${L(d)}</th>${ts.map(([t])=>`<td style="opacity:${a.filter(p=>p.domain===d&&p.instrument===t).length?1:.05}">${a.filter(p=>p.domain===d&&p.instrument===t).length||""}</td>`).join("")}</tr>`).join("")}</table>`}
function table(a){canvas.innerHTML=`<table><thead><tr><th>日期</th><th>经济体</th><th>政策</th><th>领域／工具</th><th>目的</th><th>状态</th><th>证据</th></tr></thead><tbody>${a.sort((x,y)=>y.announced.localeCompare(x.announced)).map(p=>`<tr data-id="${p.id}"><td>${p.announced}</td><td>${p.economy}</td><td><b>${p.name}</b><small>${p.authority}</small></td><td>${L(p.domain)}<small>${L(p.instrument)}</small></td><td>${L(p.rationale)}</td><td>${L(p.status)}</td><td>${p.uncertain?"状态待核验":"已核验"}</td></tr>`).join("")}</tbody></table>`;canvas.querySelectorAll("tr[data-id]").forEach(r=>r.onclick=()=>show(all.find(p=>p.id===r.dataset.id)))}
function show(p){detailbody.innerHTML=`<p>记录编号：${p.id}　经济体：${p.economy}</p><h2>${p.name}</h2><p><b>公布：</b>${p.announced}　<b>生效：</b>${p.effective||"未注明"}　<b>状态：</b>${L(p.status)}</p><h3>政策摘要</h3><p>${p.summary}</p><h3>政策分类</h3><p>${L(p.domain)} · ${L(p.instrument)} · ${L(p.direction)} · ${L(p.rationale)}</p><h3>证据</h3><a href="${p.sourceUrl}" target="_blank">查看官方原文 ↗</a><p>最后核验：${p.verified}</p>${p.notes?`<p>${p.uncertain?"待核验原因：":""}${p.notes}</p>`:""}`;detail.showModal()}
