const Z = {
  industrial_policy:"产业政策", technology:"技术", investment:"投资", trade:"贸易", energy_resources:"能源与资源", supply_chain:"供应链", data_platform:"数据与平台", international_cooperation:"国际合作", infrastructure:"基础设施", finance:"金融",
  security:"安全与韧性", resilience:"供应链韧性", competitiveness:"竞争力", human_rights:"人权", environment:"环境与气候", other:"其他",
  effective:"生效", terminated:"终止", amended:"修订", suspended:"暂停", proposed:"提议", adopted:"已通过",
  promote:"促进", restrict:"限制", defend:"防御", retaliate:"反制", cooperate:"合作", capacity_building:"能力建设",
  binding:"约束性", non_binding:"非约束性", mixed:"混合", ai_governance:"人工智能治理", carbon_border_adjustment:"碳边境调节", connected_product_restriction:"联网产品限制", critical_mineral_policy:"关键矿产政策", cross_border_data_restriction:"跨境数据限制", cross_border_data_rule:"跨境数据规则", data_access_rule:"数据访问规则", digital_technology_control:"数字技术管制", economic_security_partnership:"经济安全伙伴关系", entity_listing:"实体清单", export_control:"出口管制", financial_sanction:"金融制裁", financing_restriction:"融资限制", forced_labor_import_ban:"强迫劳动进口禁令", foreign_subsidy_review:"外国补贴审查", industrial_strategy:"产业战略", infrastructure_financing:"基础设施融资", inward_investment_screening:"外资安全审查", outbound_investment_screening:"对外投资审查", platform_restriction:"平台限制", procurement_preference:"政府采购偏好", production_mandate:"生产要求", resource_export_restriction:"资源出口限制", strategic_funding_platform:"战略融资平台", subsidy:"补贴", subsidy_guardrail:"补贴护栏", supply_chain_agreement:"供应链协议", supply_chain_review:"供应链审查", import_restriction:"进口限制", tariff:"关税", tax_incentive:"税收激励", traceability_due_diligence:"追溯与尽职调查", trade_countermeasure:"贸易反制", global:"全球", countries_of_concern:"受关注国家", China:"中国", Russia:"俄罗斯"
};
const L=x=>Z[x]||String(x||"").replaceAll("_"," ");
let all=[], view="timeline";
const $=x=>document.querySelector(x);
const statusFilter=$("#status"), closeButton=$("#close");
const counts=(a,k)=>Object.entries(a.reduce((o,p)=>{const v=p[k]||"未标明";o[v]=(o[v]||0)+1;return o},{})).sort((a,b)=>b[1]-a[1]);

fetch("./policies.json?v=4").then(r=>{if(!r.ok)throw Error(`数据读取失败：${r.status}`);return r.json()}).then(x=>{all=x;$("#total").textContent=x.length;$("#totalEconomies").textContent=new Set(x.map(p=>p.economy)).size;setup();render()}).catch(e=>{$("#canvas").innerHTML=`<p class="error">${e.message}，请刷新页面或检查数据文件。</p>`});

function options(id,items,label=true){$(id).innerHTML='<option value="全部">全部</option>'+items.map(([v,n])=>`<option value="${v}">${label?L(v):v}（${n}）</option>`).join("")}
function setup(){
  options("#economy",counts(all,"economy"),false); options("#domain",counts(all,"domain")); options("#purpose",counts(all,"rationale")); options("#status",counts(all,"status"));
  for(let y=2015;y<=2026;y++){from.add(new Option(y,y));to.add(new Option(y,y))} from.value=2015;to.value=2026;
  document.querySelectorAll("input,select").forEach(e=>e.oninput=render);
  reset.onclick=()=>{q.value="";economy.value=domain.value=purpose.value=statusFilter.value="全部";from.value=2015;to.value=2026;render()};
  document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));render()});
  closeButton.onclick=()=>detail.close();
}
function filtered(){const s=q.value.trim().toLowerCase();return all.filter(p=>(economy.value==="全部"||p.economy===economy.value)&&(domain.value==="全部"||p.domain===domain.value)&&(purpose.value==="全部"||p.rationale===purpose.value)&&(statusFilter.value==="全部"||p.status===statusFilter.value)&&+p.announced.slice(0,4)>=+from.value&&+p.announced.slice(0,4)<=+to.value&&(!s||[p.name,p.originalName,p.authority,p.summary,p.instrument,p.targetIndustry].join(" ").toLowerCase().includes(s)))}
function render(){const a=filtered();count.textContent=a.length;ecount.textContent=new Set(a.map(p=>p.economy)).size;active.textContent=a.filter(p=>p.status==="effective").length;verify.textContent=a.filter(p=>p.uncertain).length;({timeline,compare,tools,table}[view])(a)}
function economyLegend(es){return `<div class="legend">${es.map(([e],i)=>`<span><i data-i="${i%4}"></i>${e}</span>`).join("")}</div>`}
function timeline(a){const es=counts(a,"economy"),ys=[];for(let y=+from.value;y<=+to.value;y++)ys.push(y);const max=Math.max(1,...ys.flatMap(y=>es.map(([e])=>a.filter(p=>p.economy===e&&p.announced.startsWith(String(y))).length)));canvas.innerHTML=`<div class="timeline">${economyLegend(es)}${ys.map(y=>`<div class="yearrow"><b>${y}</b><div>${es.map(([e],i)=>{const n=a.filter(p=>p.economy===e&&p.announced.startsWith(String(y))).length;return n?`<button data-i="${i%4}" style="width:${Math.max(4,n/max*100)}%" title="${y}年 ${e}：${n}项">${e} ${n}</button>`:""}).join("")}</div></div>`).join("")}</div>`}
function compare(a){const es=counts(a,"economy"),ds=counts(a,"domain"),m=Math.max(1,...es.map(x=>x[1]));canvas.innerHTML=`<div class="compare"><h2>经济体政策构成</h2>${es.map(([e,n])=>`<div class="compareblock"><header><b>${e}</b><span>${n}项</span></header><div class="stack">${ds.map(([d])=>{const c=a.filter(p=>p.economy===e&&p.domain===d).length;return c?`<i title="${L(d)} ${c}" style="width:${c/n*100}%"></i>`:""}).join("")}</div><div class="rankbar" style="width:${n/m*100}%"></div></div>`).join("")}</div>`}
function tools(a){const ds=counts(a,"domain"),ts=counts(a,"instrument").slice(0,12),max=Math.max(1,...ds.flatMap(([d])=>ts.map(([t])=>a.filter(p=>p.domain===d&&p.instrument===t).length)));canvas.innerHTML=`<div class="matrixwrap"><h2>领域 × 政策工具</h2>${economyLegend(counts(a,"economy"))}<div class="matrix" style="grid-template-columns:150px repeat(${ts.length},minmax(110px,1fr))"><span></span>${ts.map(([t])=>`<b>${L(t)}</b>`).join("")}${ds.map(([d])=>`<strong>${L(d)}</strong>${ts.map(([t])=>{const n=a.filter(p=>p.domain===d&&p.instrument===t).length;return `<i style="opacity:${n?.18+.82*n/max:0}">${n||""}</i>`}).join("")}`).join("")}</div></div>`}
function table(a){canvas.innerHTML=`<div class="tablewrap"><table><thead><tr><th>日期</th><th>经济体</th><th>政策</th><th>领域／工具</th><th>目的</th><th>状态</th><th>证据</th></tr></thead><tbody>${[...a].sort((x,y)=>y.announced.localeCompare(x.announced)).map(p=>`<tr data-id="${p.id}"><td>${p.announced}</td><td>${p.economy}</td><td><b>${p.name}</b><small>${p.authority}</small></td><td>${L(p.domain)}<small>${L(p.instrument)}</small></td><td>${L(p.rationale)}</td><td><span class="status-pill ${p.status}">${L(p.status)}</span></td><td>${p.uncertain?"状态待核验":"已核验"}</td></tr>`).join("")}</tbody></table></div>`;canvas.querySelectorAll("tr[data-id]").forEach(r=>r.onclick=()=>show(all.find(p=>p.id===r.dataset.id)))}
function show(p){detailbody.innerHTML=`<p>记录编号：${p.id}　经济体：${p.economy}</p><h2>${p.name}</h2><p><b>公布：</b>${p.announced}　<b>生效：</b>${p.effective||"未注明"}　<b>状态：</b>${L(p.status)}</p><h3>政策摘要</h3><p>${p.summary}</p><h3>政策分类</h3><p>${L(p.domain)} · ${L(p.instrument)} · ${L(p.direction)} · ${L(p.rationale)}</p><h3>证据</h3><a href="${p.sourceUrl}" target="_blank" rel="noopener">查看官方原文 →</a><p>最后核验：${p.verified}</p>${p.notes?`<p>${p.uncertain?"待核验原因：":""}${p.notes}</p>`:""}`;detail.showModal()}
